### ISSUE TITLE
gui TypeError: fetch failed

### ISSUE THREAD

**Issue by AutumnStack** [maximemoreillon/chartmuseum-gui#2]
Have you ever encountered this? When I use the backend version ghcr.io/helm/chartmuseum:v0.16.0, the access page displays a 500 error. The following is the container log：
`TypeError: fetch failed
    at fetch (file:///app/build/shims.js:20794:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.fetch (file:///app/build/server/index.js:3487:12)
    at async load (file:///app/build/server/chunks/3-4523046e.js:4:15)
    at async load_server_data (file:///app/build/server/index.js:1797:18)
    at async Promise.all (index 1)
    at async render_data (file:///app/build/server/index.js:2941:19)
    at async resolve (file:///app/build/server/index.js:3812:22)
    at async respond (file:///app/build/server/index.js:3715:22)
    at async Array.ssr (file:///app/build/handler.js:1190:3)`

**Comment by maximemoreillon** [comment]
Hello

Thank you for raising this issue

I tried using the image `moreillon/chartmuseum-gui:ca3d63b4` with ChartMuseum `ghcr.io/helm/chartmuseum:v0.16.0` and it worked without problems.

I am not sure why it fails on your side
